/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import Cartridge_pkg.Cartridge;
import Instrument_pkg.Instrument;
import JDBCqueries_pkg.JDBCqueries;
import TestInstance_pkg.TestInstance;
import java.util.ArrayList;

/**
 *
 * @author Owner
 */
public class Dashboard_presentation extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_presentation
     */
    public Dashboard_presentation() {
        initComponents();

        try {
            this.updateInstrumentPanel();

        } catch (Exception e) {
            // handle the error
            System.out.println("\n" + "Dashboard_presentation General Exception " + e.getMessage());
            System.exit(0);
        } finally {
            //finally block used to close resources

        }   //end finally
    }

    private void updateInstrumentPanel() {

        try {
            JDBCqueries queries = new JDBCqueries();
            ArrayList<String> arrayList;

            arrayList = queries.getAllInstrumentIDs();

            for (String ID : arrayList) {
                this.instrumentTextArea.setText(this.instrumentTextArea.getText() + ID + "\n");
            }
            
        } catch (Exception e) {
            // handle the error
            System.out.println("\n" + "updateInstrumentPanel General Exception " + e.getMessage());
            System.exit(0);
        } finally {
            //finally block used to close resources

        }   //end finally

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        instrumentPanel = new javax.swing.JPanel();
        instrumentLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        instrumentTextArea = new javax.swing.JTextArea();
        cartridgePanel = new javax.swing.JPanel();
        cartridgeLabel = new javax.swing.JLabel();
        Tests = new javax.swing.JPanel();
        testLabel = new javax.swing.JLabel();
        patientPanel = new javax.swing.JPanel();
        patientLabel = new javax.swing.JLabel();
        lowerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SensoDx Dashboard");
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        topPanel.setBackground(new java.awt.Color(255, 255, 102));
        topPanel.setLayout(new java.awt.GridLayout());

        instrumentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        instrumentLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        instrumentLabel.setText("Instrument");

        instrumentTextArea.setColumns(20);
        instrumentTextArea.setRows(5);
        jScrollPane1.setViewportView(instrumentTextArea);

        javax.swing.GroupLayout instrumentPanelLayout = new javax.swing.GroupLayout(instrumentPanel);
        instrumentPanel.setLayout(instrumentPanelLayout);
        instrumentPanelLayout.setHorizontalGroup(
            instrumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(instrumentPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(instrumentLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        instrumentPanelLayout.setVerticalGroup(
            instrumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrumentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instrumentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        instrumentLabel.getAccessibleContext().setAccessibleName("Instruments");

        topPanel.add(instrumentPanel);

        cartridgePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cartridgeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cartridgeLabel.setText("Cartridges");

        javax.swing.GroupLayout cartridgePanelLayout = new javax.swing.GroupLayout(cartridgePanel);
        cartridgePanel.setLayout(cartridgePanelLayout);
        cartridgePanelLayout.setHorizontalGroup(
            cartridgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartridgePanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(cartridgeLabel)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        cartridgePanelLayout.setVerticalGroup(
            cartridgePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartridgePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cartridgeLabel)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        topPanel.add(cartridgePanel);

        Tests.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        testLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        testLabel.setText("Tests");

        javax.swing.GroupLayout TestsLayout = new javax.swing.GroupLayout(Tests);
        Tests.setLayout(TestsLayout);
        TestsLayout.setHorizontalGroup(
            TestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestsLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(testLabel)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        TestsLayout.setVerticalGroup(
            TestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testLabel)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        topPanel.add(Tests);

        patientPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        patientLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patientLabel.setText("Patients");

        javax.swing.GroupLayout patientPanelLayout = new javax.swing.GroupLayout(patientPanel);
        patientPanel.setLayout(patientPanelLayout);
        patientPanelLayout.setHorizontalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(patientLabel)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        patientPanelLayout.setVerticalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientLabel)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        topPanel.add(patientPanel);

        getContentPane().add(topPanel);

        lowerPanel.setBackground(new java.awt.Color(204, 204, 255));
        lowerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout lowerPanelLayout = new javax.swing.GroupLayout(lowerPanel);
        lowerPanel.setLayout(lowerPanelLayout);
        lowerPanelLayout.setHorizontalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 927, Short.MAX_VALUE)
        );
        lowerPanelLayout.setVerticalGroup(
            lowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        getContentPane().add(lowerPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_presentation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tests;
    private javax.swing.JLabel cartridgeLabel;
    private javax.swing.JPanel cartridgePanel;
    private javax.swing.JLabel instrumentLabel;
    private javax.swing.JPanel instrumentPanel;
    private javax.swing.JTextArea instrumentTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lowerPanel;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JPanel patientPanel;
    private javax.swing.JLabel testLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
